---
name: Build docker image and push AWS Deployment ECS

on:
  release:
    types: [published, created, edited]

jobs:
  push_to_registry:
    name: Build and Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ../../../
          tags: ghcr.io/denzuko/clients/rearc.io
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true

  terraform:
    name: 'Build Infrastructure'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner
    # is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    # Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install the latest version of Terraform CLI and configure
      # the Terraform CLI configuration file with a Terraform Cloud
      # user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # Initialize a new or existing Terraform working directory by creating
      # initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
      # Checks that all Terraform configuration files adhere
      # to a canonical format
      - name: Terraform Format
        run: terraform fmt -check
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR__AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          TF_VAR__AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          TF_VAR__AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          TF_VAR__image_name: ghcr.io/denzuko/clients/rearc.io:latest

  newman:
    name: 'Validate deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 484495-56c2adc0-0c58-4f36-9c9d-cc0bcc734e10
          environment: 484495-51b5f716-8dba-4adb-931a-2eafc13a17f9
...
